version: '3.5'
services:
  app:
    image: node:16.20.0
    container_name: app
    ports:
      - 3000:3000
    working_dir: /src
    command: bash -c "npm install --force && npm run dev"
    volumes:
      - './:/src'
    environment:
      HOST: 0.0.0.0
